# config/params.yaml
bus_master:
  ros__parameters:
    # Activate the subscription to the cmd_vel command which will be dispatched to the motor
    enable_twist: true
    # Enable the publishing of the odometry infiormation via events.
    enable_odom: true
    # Frequency to publish odometry infiormation. Publishing will disbaled, when set to 0.0
    publish_odom_frequency : 10.0
    # Enable the publishing of the motor speed information via events.
    enable_speed: true
    # When enabled publish
    publish_current_speed_frequency: 10.0
    # Enable the publishing of the motor status information via events.
    enable_status: true
    # Frequency to publish motor status information like used current. Publishing will disbaled, when set to 0.0
    publish_motor_status_frequency: 10.0
    # Acceleration Rate 
    # If you require a controlled acceleration period for the attached motors to reach there ultimate speed, the MD25 has a register to provide this. 
    # It works by using a value into the acceleration register and incrementing the power by that value. Changing between the current speed of the motors 
    # and the new speed (from speed 1 and 2 registers). So if the motors were traveling at full speed in the forward direction (255) and were instructed 
    # to move at full speed in reverse (0), there would be 255 steps with an acceleration register value of 1, but 128 for a value of 2. 
    # The default acceleration value is 5, meaning the speed is changed from full forward to full reverse in 1.25 seconds. 
    # The register will accept values of 1 up to 10 which equates to a period of only 0.65 seconds to travel from full speed in one direction to full speed in the opposite direction.
    acceleration_rate: 3